# Generated by Django 5.1.7 on 2025-03-14 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_review_options_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='product.category'),
        ),
        migrations.AddField(
            model_name='brand',
            name='characteristics',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
